### PR TITLE
Vim Mode: Enable with keyboard shortcut

### PR DESCRIPTION
**Pull request by bkimmig**
# What

Add "extras" menu drop down with "vim mode".

Selecting the drop down gives you the opportunity to "Enable Vim Mode"

enable-vim-mode

Once enabled the dropdown gives you the choice to "Disable Vim Mode"

disable-vim-mode

<details>
    <summary> First Proposal - Click to Expand </summary>

**See discussion below for reasons we did not do this**

Add a keyboard shortcut to enable/disable the existing `vimMode`.

- Used `:` as the hot key
  + felt right in the framing of vim
  + requires a user to press two keys to enable - less likely to happen by accident
- Added status to the info tool bar so you can see the state
- Can toggle on/off regardless of which mode you are in

## Vim Disabled
vim-disabled

## Vim Enabled
vim-enabled
</details>

### CODE REVIEW

**Comment by stevenhao** [comment]
hmm, i feel like it could still be pressed on accident. also, : doesn't seem like the right toggle since it's more of a thing you do once you're in vim already?

i don't have any good suggestions on what would be a good hotkey though... maybe a button under a menu somewhere.

**Comment by bkimmig** [comment]
>i feel like it could still be pressed on accident.

Yeah, you are totally correct here after I play tested a bit more.

>i don't have any good suggestions on what would be a good hotkey though... maybe a button under a menu somewhere.

I figured since it was removed from the menu it shouldn't live there, but if you'd be ok w/ it in the menu I'd be happy to add it somewhere in there.

Alternatively we could make the hot key combo more complex so you need like 3 keys or more to avoid accidental toggling? `ctrl-alt-V` or something in that sort of space?

However, if you are more of the mind that "this isn't a feature we want" that is fine and I can move on :).

**Comment by stevenhao** [comment]
> However, if you are more of the mind that "this isn't a feature we want" that is fine and I can move on :).

Personally, I like vim mode enough that i want it to exist and be somewhat discoverable (not necessarily on their first experience -- maybe on a user's 10-50th game or something). i don't personally use it (though i do use vim for programming) but i know there are users (e.g. in the discord) who do use it.

I moved it out of the "Modes Dropdown Menu" as part of a redesign of the toolbar (moving more towards icons & making color attribution its own menu button). Perhaps we should add a button to the toolbar that, when clicked, drops down a menu of "Other stuff", where we hide all the uncommonly used features :)

**Comment by bkimmig** [comment]
>For vim mode, and other "niche features" Perhaps we should add a button to the toolbar that, when clicked, drops down a menu of "Other stuff", where we hide all the uncommonly used features :)

Sounds good to me. I'll close out this request and start that as a feature if that is ok?

**Comment by stevenhao** [comment]
sure, or repurpose this PR to keep discussion in one place

**Comment by bkimmig** [comment]
@stevenhao I've updated the PR description (collapsed the old one, but kept it). What do you think of this solution?

**Comment by stevenhao** [comment]
OK! I may want to change this to an icon in the future, for the sake of saving toolbar space. Down to merge this as-is for now. Thanks for working on this!

**Comment by stevenhao** [comment]
I might also add Color Attribution Mode, List View Mode, Autocheck here too to improve their discoverability. They already have icons in the toolbar, but it's not always obvious how to use them at first glance.

**Pull request merged**
