### PR TITLE
Add autocheck button to mobile toolbar.

### PR DESCRIPTION
**Pull request by flackr**
This adds the autocheck button to the expanded menu on the mobile toolbar with updated styling to make its state visible above the blue menubar.

### CODE REVIEW

**Comment by flackr** [comment]
My friends and I really like the autocheck feature. If you find the second page of the toolbar is getting too crowded we could always either add a menu or make the expand button move between two or more additional menu panes.

**Comment by 5hubh4m** [comment]
I love auto check, so I would really appreciate it if this PR was merged into the main deployment.

However, the current implementation seems to have a bug where there’s a small chance an entered letter does not auto check and remains black. If you backspace and type it again it auto checks correctly.

**Comment by flackr** [comment]
> However, the current implementation seems to have a bug where there’s a small chance an entered letter does not auto check and remains black. If you backspace and type it again it auto checks correctly.

This is true, however this is an issue with autocheck already (outside of this PR) and should be treated as a separate issue / pull request to fix.

**Comment by 5hubh4m** [comment]
Yes I realised that after I looked at the commit!

**Comment by stevenhao** [comment]
lgtm!

**Pull request merged**
